import type { Metadata } from "next";
import { Lato, Inter } from "next/font/google";
import "./globals.css";

const latoSans = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"], // Available weights for Lato
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Available weights for Inter
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${latoSans.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
